from pgmpy.models import BayesianModel
import pandas as pd
import numpy as np
from pgmpy.factors.discrete import TabularCPD


def create_model():
	edges_list = [('cebolla', 'distensionAbdominal'),
				  ('cebolla', 'borborigmos'),
				  ('cafe', 'reflujoGastroesofagico'),
				  ('cafe', 'dolorAbdominal'),
				  ('frijol', 'distensionAbdominal'),
				  ('frijol', 'flatulencia'),
				  ('aji', 'sintomasDispepsicos'),
				  ('aji','dolorAbdominal'),
				  ('leche', 'diarrea'),
				  ('leche', 'intolerancia'),
				  ('tomate', 'intolerancia'),
				  ('te','estrenimiento'),
				  ('manzana','borborigmos'),
				  ('ajo','flatulencia'),
				  ('trigo','sintomasDispepsicos'),
				  ('trigo','diarrea')]
	model = BayesianModel(edges_list)
	nodes = {'avena': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'trigo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'aji': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'ajo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'acelga': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'albahaca': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'apio': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'brocoli': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'caigua': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'calabaza': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'camucamu': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'coco': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'fresa': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'granadilla': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'higo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'lima': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'limon': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'lucuma': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'mandarina': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'mango': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'maracuya': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'melon': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'naranja': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'manzana': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'almendras': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'arroz': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'cafe': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'cebolla': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'cerveza': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'chirimoya': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'chocolate': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'conejo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'res': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pan': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'huevo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'jamon': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'leche': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'leche_cabra': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'lechuga': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'lentejas': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'mantequilla': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'miel': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'palta': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pavo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pato': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'papa': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pejerrey': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pera': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pina': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'platano': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pimiento': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pollo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'queso': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'quinua': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'salchicha': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'te': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'tocino': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'tomate': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'sandia': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'cerdo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'sardina': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'uva': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'venado': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'vino': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'yogurt': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'zapallo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'zanahoria': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pepinillo': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'vainitas': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'frijol': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'pallar': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'distensionAbdominal': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'flatulencia': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'dolorAbdominal': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'sintomasDispepsicos': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'estrenimiento': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},						
			'diarrea': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},						
			'intolerancia': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},
			'borborigmos': {'States': {'bajo', 'medio','alto'},
						'type': 'discrete'},					
						}
	model.add_nodes_from(nodes)


	cpds = [{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'avena':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'acelga':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'albahaca':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'apio':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'brocoli':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'caigua':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'calabaza':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'camucamu':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'coco':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'fresa':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'granadilla': []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'higo':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'lima':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'limon':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'lucuma':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'mandarina':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'mango':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'maracuya':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'melon':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'naranja':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'manzana':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'almendras':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'arroz':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'cafe':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'cebolla':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'cerveza':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'chirimoya':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'chocolate':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'conejo':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'res':        []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pan':        []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'huevo':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'jamon':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'leche':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'leche_cabra':[]}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'lechuga':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'lentejas':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'mantequilla': []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'miel':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'palta':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pavo':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pato':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'papa':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pejerrey':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pera':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pina':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'platano':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pimiento':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pollo':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'queso':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'quinua':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'salchicha':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'te':         []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'tocino':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'tomate':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'sandia':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'cerdo':      []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'sardina':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'uva':        []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'venado':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'vino':       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'yogurt':     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'zapallo':    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'zanahoria':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pepinillo':  []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'vainitas':   []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'frijol' :    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'pallar' :    []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'trigo' :     []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'aji' :       []}},
			{'Values': np.array([[0.3], [0.4],[0.3]]),'Variables': {'ajo' :    []}}]

	tabular_cpds = []
	for cpd in cpds:
		var = list(cpd['Variables'].keys())[0]
		evidence = cpd['Variables'][var]
		values = cpd['Values']
		states = len(nodes[var]['States'])
		evidence_card = [len(nodes[evidence_var]['States'])
						 for evidence_var in evidence]
		tabular_cpds.append(
			TabularCPD(var, states, values, evidence, evidence_card))

	model.add_cpds(*tabular_cpds)	


	cpd_distension = TabularCPD(variable='distensionAbdominal', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['cebolla','frijol'],
							evidence_card=[3, 3])  


	cpd_sintDisp = TabularCPD(variable='sintomasDispepsicos', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['aji', 'trigo'],
							evidence_card=[3, 3])  
	cpd_intolerancia = TabularCPD(variable='intolerancia', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['leche', 'tomate'],
							evidence_card=[3, 3])  
	cpd_borborigmos = TabularCPD(variable='borborigmos', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['manzana','cebolla'],
							evidence_card=[3, 3])  
	cpd_estren = TabularCPD(variable='estrenimiento', variable_card=3,
							values=[[0.15, 0.3,0.55],
									[0.65, 0.3,0.05],
									[0.2, 0.4,0.4]],
							evidence=['te'],
							evidence_card=[3]) 
	cpd_reflujo = TabularCPD(variable='reflujoGastroesofagico', variable_card=3,
							 values=[[0.15, 0.3,0.55],
									[0.65, 0.3,0.05],
									[0.2, 0.4,0.4]],
							evidence=['cafe'],
							evidence_card=[3]) 
	cpd_flat = TabularCPD(variable='flatulencia', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['ajo','frijol'],
							evidence_card=[3, 3])  
	cpd_dolor = TabularCPD(variable='dolorAbdominal', variable_card=3,
							values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['cafe','aji'],
							evidence_card=[3, 3])  

	cpd_diarrea = TabularCPD(variable='diarrea', variable_card=3,
						   values=[[0.6, 0.3,0.1,0.65, 0.3,0.05,0.65, 0.3,0.05],
									[0.2, 0.3,0.5,0.25, 0.4,0.35,0.05, 0.3,0.65],
									[0.2, 0.4,0.4,0.1, 0.3,0.60,0.3, 0.4,0.3]],
							evidence=['leche','trigo'],
							evidence_card=[3, 3])  				
							
	model.add_cpds(cpd_distension, cpd_sintDisp, cpd_intolerancia, cpd_estren, cpd_borborigmos,cpd_reflujo,cpd_dolor,cpd_flat,cpd_diarrea)
	model.check_model()
	return model
